apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfm-auth
  namespace: argocd
spec:
  destination:
    namespace: gflex-hom
    server: https://kubernetes.default.svc
  project: gflex
  source:
    path: src/gestaoflex/pfm-auth/hom
    repoURL: git@github.com:marcelodeassis1/gestaoflex.git
    targetRevision: HEAD
    
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfm-auth
  namespace: argocd
spec:
  destination:
    namespace: gflex
    server: https://kubernetes.default.svc
  project: gflex
  source:
    path: src/gestaoflex/pfm-auth/prd
    repoURL: git@github.com:marcelodeassis1/gestaoflex.git
    targetRevision: HEAD
    
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true