apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfm-manager-hom
  namespace: argocd
spec:
  destination:
    namespace: gflex-hom
    server: https://kubernetes.default.svc
  project: gflex
  source:
    path: src/gestaoflex/pfm-manager/hom
    repoURL: git@github.com:marcelodeassis1/gestaoflex_cd.git
    targetRevision: HEAD
    
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfm-manager
  namespace: argocd
spec:
  destination:
    namespace: gflex
    server: https://kubernetes.default.svc
  project: gflex
  source:
    path: src/gestaoflex/pfm-manager/prd
    repoURL: git@github.com:marcelodeassis1/gestaoflex_cd.git
    targetRevision: HEAD
    
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true