# Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: gflex-hom
  name: adm-foundation
  labels: 
    app: adm-foundation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adm-foundation
  template:
    metadata:
      labels:
        app: adm-foundation
    spec:
      containers:
      - name: adm-foundation-container
        image: gestaoflex/adm-foundation:latest
        env:
          - name: URL_DATABASE
            valueFrom: 
              secretKeyRef:
                key: conn_db_client
                name: gflex-hom-connect
          - name: URL_BROKER
            valueFrom: 
              secretKeyRef:                
                key: conn_broker
                name: gflex-hom-connect
          - name: OTEL_EXPORTER_ENDPOINT
            value: http://loki-tempo:14268/tempo/api/traces                
        ports: 
          - containerPort: 3303
  