name: ADM-Foundation

on:
  repository_dispatch:
    types: 
      - adm-foundation
jobs:
  ######################################################################
  #######                        PRODUÇÃO                       ########
  ######################################################################
  deploy_prd:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v3

    # ADM-FOUNDATION
    - name: Update Version - adm-foundation (prd)
      if: ${{ github.event.client_payload.app == 'adm-foundation' }}  
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i src/gestaoflex/adm-foundation/prd/k8s-deployment.yaml


    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes

  ######################################################################
  #######                        HOMOLOGACAO                    ########
  ######################################################################
  deploy_hom:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'refs/heads/develop' }}

    steps:
    - uses: actions/checkout@v3


    # ADM-FOUNDATION
    - name: Update Version - adm-foundation (hom)
      if: ${{ github.event.client_payload.app == 'adm-foundation' }}  
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i src/gestaoflex/adm-foundation/hom/k8s-deployment.yaml

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
