name: PFM-Notify

on:
  repository_dispatch:
    types: 
      - pfm-notify
jobs:
  ######################################################################
  #######                        PRODUÇÃO                       ########
  ######################################################################
  deploy_prd:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v3

     # PFM-NOTIFY
    - name: Update Version - pfm-notify (prd)
      if: ${{ github.event.client_payload.app == 'pfm-notify' }}  
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i src/gestaoflex/pfm-notify/prd/k8s-deployment.yaml



    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes

  ######################################################################
  #######                        HOMOLOGACAO                    ########
  ######################################################################
  deploy_hom:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.branch == 'refs/heads/develop' }}

    steps:
    - uses: actions/checkout@v3

    # PFM-NOTIFY
    - name: Update Version - pfm-notify (hom)
      if: ${{ github.event.client_payload.app == 'pfm-notify' }}  
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i src/gestaoflex/pfm-notify/hom/k8s-deployment.yaml



    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
